name: Automailer Juan Mensajeria

on:
  schedule:
    # Ejecutar todos los días a las 13:00 UTC (aprox 9:00 AM hora local)
    - cron: "0 13 * * *"
  workflow_dispatch: # Permite ejecutar manualmente desde la pestaña "Actions"

jobs:
  run-automailer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automailer
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          DRY_RUN: "False"
        run: python automailer.py
